name = "fitai-web"
compatibility_date = "2024-12-30"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = ".vercel/output/static"

[vars]
ENVIRONMENT = "development"
NEXT_PUBLIC_API_URL = "http://localhost:8787"
NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY = "pk_test_development_key"

# Routes configuration for custom domains
[env.production]
name = "fitai-web-production"
routes = [
  { pattern = "getfitia.com/*", zone_name = "getfitia.com" },
  { pattern = "www.getfitia.com/*", zone_name = "getfitia.com" }
]

[env.production.vars]
ENVIRONMENT = "production"
NEXT_PUBLIC_API_URL = "https://api.getfitia.com"
NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY = "pk_live_your_clerk_key_here"

[env.staging]
name = "fitai-web-staging"
routes = [
  { pattern = "staging.getfitia.com/*", zone_name = "getfitia.com" }
]

[env.staging.vars]
ENVIRONMENT = "staging"
NEXT_PUBLIC_API_URL = "https://api-staging.getfitia.com"
NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY = "pk_test_development_key"