name = "fitai-api"
main = "dist/index.js"
compatibility_date = "2024-12-30"
compatibility_flags = ["nodejs_compat"]

[vars]
ENVIRONMENT = "development"

# KV Namespace for caching
[[kv_namespaces]]
binding = "CACHE"
id = "7a248575697e448b8e2a008734bdc6d3"
preview_id = "7a248575697e448b8e2a008734bdc6d3"

# D1 Database binding (if using D1 instead of external DB)
# [[d1_databases]]
# binding = "DB"
# database_name = "fitai-db"
# database_id = "your-d1-database-id"

# Routes configuration (optional - can be configured in Cloudflare dashboard)
# [[routes]]
# pattern = "api.fitai.cl/*"
# zone_name = "fitai.cl"

[env.production]
name = "fitai-api-production"

[env.production.vars]
ENVIRONMENT = "production"

# Production KV namespace
[[env.production.kv_namespaces]]
binding = "CACHE"
id = "49fe0605b32d4013b8897040197cf3ad"

[env.staging]
name = "fitai-api-staging"

[env.staging.vars]
ENVIRONMENT = "staging"

# Staging KV namespace
[[env.staging.kv_namespaces]]
binding = "CACHE"
id = "your-staging-kv-namespace-id"