name: Deploy FitAI Monorepo

on:
  push:
    branches:
      - main
  workflow_dispatch: # Allows manual triggering

jobs:
  # Check what changed to determine what to deploy
  changes:
    runs-on: ubuntu-latest
    outputs:
      api: ${{ steps.filter.outputs.api }}
      web: ${{ steps.filter.outputs.web }}
    steps:
      - uses: actions/checkout@v4
      - uses: dorny/paths-filter@v2
        id: filter
        with:
          filters: |
            api:
              - 'apps/api/**'
              - 'packages/**'
              - 'package.json'
              - 'package-lock.json'
              - 'turbo.json'
            web:
              - 'apps/web/**'
              - 'packages/**'
              - 'package.json'
              - 'package-lock.json'
              - 'turbo.json'

  # Deploy API if changes detected
  deploy-api:
    needs: changes
    if: ${{ needs.changes.outputs.api == 'true' }}
    runs-on: ubuntu-latest
    name: Deploy API to Cloudflare Workers
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18.17.0'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build API
        run: npm run build:api

      - name: Deploy to Cloudflare Workers
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          workingDirectory: 'apps/api'
          command: deploy src/index.ts
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          JWT_SECRET: ${{ secrets.JWT_SECRET }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          MERCADOPAGO_ACCESS_TOKEN: ${{ secrets.MERCADOPAGO_ACCESS_TOKEN }}

  # Note: Web deployment is handled automatically by Cloudflare Pages GitHub integration
  # This job is just for notification purposes
  notify-web-deployment:
    needs: changes
    if: ${{ needs.changes.outputs.web == 'true' }}
    runs-on: ubuntu-latest
    name: Web Deployment Notification
    steps:
      - name: Web deployment triggered
        run: |
          echo "Web frontend changes detected."
          echo "Cloudflare Pages will automatically deploy via GitHub integration."